@startuml
class Libro {
    -titulo: String
    -autor: String
    -Anio: int
    +getTitulo(): String
    +setTitulo(nuevoTitulo: String): void
    +getAutor(): String
    +setAutor(nuevoAutor: String): void
    +getAnio(): int
    +setAnio(nuevoAnio: int): void
}
@enduml